export type CharacterPattern = 'coffee' | 'sparkle' | 'route' | 'breakfast' | 'rain' | 'transit' | 'chip' | 'family' | 'border' | 'shield' | 'craft' | 'tea' | 'puppet' | 'rice' | 'cloud' | 'sugar' | 'port' | 'sun' | 'leaf' | 'ticket' | 'wave' | 'sail' | 'jar' | 'lighthouse';

export interface Character {
  id: number;
  region: string;
  job: string;
  quote: string;
  zone: string;
  bg: string;
  panel: string;
  ink: string;
  accent: string;
  pattern: CharacterPattern;
  sheet: string;
  spriteX: number;
  spriteY: number;
}

export const CHARACTERS: Character[] = [
  {
    "id": 1,
    "region": "天母",
    "job": "午茶結界師",
    "quote": "別急，先喝杯咖啡。",
    "zone": "北部",
    "bg": "#F4845F",
    "panel": "#F79B7F",
    "accent": "#843B25",
    "ink": "#203C32",
    "pattern": "coffee",
    "sheet": "regions-01.png",
    "spriteX": 0,
    "spriteY": 0
  },
  {
    "id": 2,
    "region": "信義",
    "job": "時尚召喚師",
    "quote": "出門就是我的伸展台。",
    "zone": "北部",
    "bg": "#E882B4",
    "panel": "#ED9DC4",
    "accent": "#833857",
    "ink": "#203C32",
    "pattern": "sparkle",
    "sheet": "regions-01.png",
    "spriteX": 50,
    "spriteY": 0
  },
  {
    "id": 3,
    "region": "中和",
    "job": "迷宮導航師",
    "quote": "這條巷子，我熟。",
    "zone": "北部",
    "bg": "#6EB5FF",
    "panel": "#8DC4FF",
    "accent": "#24568A",
    "ink": "#203C32",
    "pattern": "route",
    "sheet": "regions-01.png",
    "spriteX": 100,
    "spriteY": 0
  },
  {
    "id": 4,
    "region": "永和",
    "job": "早餐聖騎士",
    "quote": "先吃飽，再開打。",
    "zone": "北部",
    "bg": "#F4845F",
    "panel": "#F79B7F",
    "accent": "#843B25",
    "ink": "#203C32",
    "pattern": "breakfast",
    "sheet": "regions-01.png",
    "spriteX": 0,
    "spriteY": 100
  },
  {
    "id": 5,
    "region": "基隆",
    "job": "雨霧守護者",
    "quote": "這點雨，也算下雨？",
    "zone": "北部",
    "bg": "#6EB5FF",
    "panel": "#8DC4FF",
    "accent": "#24568A",
    "ink": "#203C32",
    "pattern": "rain",
    "sheet": "regions-01.png",
    "spriteX": 50,
    "spriteY": 100
  },
  {
    "id": 6,
    "region": "桃園",
    "job": "轉乘領航員",
    "quote": "下一站，我來帶路。",
    "zone": "北部",
    "bg": "#6EB5FF",
    "panel": "#8DC4FF",
    "accent": "#24568A",
    "ink": "#203C32",
    "pattern": "transit",
    "sheet": "regions-01.png",
    "spriteX": 100,
    "spriteY": 100
  },
  {
    "id": 7,
    "region": "新竹市",
    "job": "晶片風法師",
    "quote": "風再大，程式照跑。",
    "zone": "北部",
    "bg": "#6BBF7A",
    "panel": "#85CC92",
    "accent": "#2E6038",
    "ink": "#203C32",
    "pattern": "chip",
    "sheet": "regions-02.png",
    "spriteX": 0,
    "spriteY": 0
  },
  {
    "id": 8,
    "region": "竹北",
    "job": "育兒機甲師",
    "quote": "接送排程，比開會還滿。",
    "zone": "北部",
    "bg": "#E882B4",
    "panel": "#ED9DC4",
    "accent": "#833857",
    "ink": "#203C32",
    "pattern": "family",
    "sheet": "regions-02.png",
    "spriteX": 50,
    "spriteY": 0
  },
  {
    "id": 9,
    "region": "苗栗",
    "job": "邊境通關官",
    "quote": "歡迎入境苗栗國。",
    "zone": "中部",
    "bg": "#6BBF7A",
    "panel": "#85CC92",
    "accent": "#2E6038",
    "ink": "#203C32",
    "pattern": "border",
    "sheet": "regions-02.png",
    "spriteX": 100,
    "spriteY": 0
  },
  {
    "id": 10,
    "region": "台中",
    "job": "豪氣重裝騎士",
    "quote": "排場可以，氣勢要滿。",
    "zone": "中部",
    "bg": "#F4845F",
    "panel": "#F79B7F",
    "accent": "#843B25",
    "ink": "#203C32",
    "pattern": "shield",
    "sheet": "regions-02.png",
    "spriteX": 0,
    "spriteY": 100
  },
  {
    "id": 11,
    "region": "彰化",
    "job": "隱富鍛造師",
    "quote": "穿拖鞋，也能當老闆。",
    "zone": "中部",
    "bg": "#F4845F",
    "panel": "#F79B7F",
    "accent": "#843B25",
    "ink": "#203C32",
    "pattern": "craft",
    "sheet": "regions-02.png",
    "spriteX": 50,
    "spriteY": 100
  },
  {
    "id": 12,
    "region": "南投",
    "job": "山林茶術師",
    "quote": "我住山裡，也看過海。",
    "zone": "中部",
    "bg": "#6BBF7A",
    "panel": "#85CC92",
    "accent": "#2E6038",
    "ink": "#203C32",
    "pattern": "tea",
    "sheet": "regions-02.png",
    "spriteX": 100,
    "spriteY": 100
  },
  {
    "id": 13,
    "region": "雲林",
    "job": "田野操偶師",
    "quote": "田裡有糧，掌上有戲。",
    "zone": "中部",
    "bg": "#6BBF7A",
    "panel": "#85CC92",
    "accent": "#2E6038",
    "ink": "#203C32",
    "pattern": "puppet",
    "sheet": "regions-03.png",
    "spriteX": 0,
    "spriteY": 0
  },
  {
    "id": 14,
    "region": "嘉義市",
    "job": "雞肉飯鑑定師",
    "quote": "這碗，我有意見。",
    "zone": "南部",
    "bg": "#F4845F",
    "panel": "#F79B7F",
    "accent": "#843B25",
    "ink": "#203C32",
    "pattern": "rice",
    "sheet": "regions-03.png",
    "spriteX": 50,
    "spriteY": 0
  },
  {
    "id": 15,
    "region": "嘉義縣",
    "job": "雲海茶牧師",
    "quote": "先喝茶，再慢慢講。",
    "zone": "南部",
    "bg": "#6EB5FF",
    "panel": "#8DC4FF",
    "accent": "#24568A",
    "ink": "#203C32",
    "pattern": "cloud",
    "sheet": "regions-03.png",
    "spriteX": 100,
    "spriteY": 0
  },
  {
    "id": 16,
    "region": "台南",
    "job": "糖霜煉金師",
    "quote": "這樣才叫微糖。",
    "zone": "南部",
    "bg": "#E882B4",
    "panel": "#ED9DC4",
    "accent": "#833857",
    "ink": "#203C32",
    "pattern": "sugar",
    "sheet": "regions-03.png",
    "spriteX": 0,
    "spriteY": 100
  },
  {
    "id": 17,
    "region": "高雄",
    "job": "烈日港口衛士",
    "quote": "二十度？先穿外套。",
    "zone": "南部",
    "bg": "#6EB5FF",
    "panel": "#8DC4FF",
    "accent": "#24568A",
    "ink": "#203C32",
    "pattern": "port",
    "sheet": "regions-03.png",
    "spriteX": 50,
    "spriteY": 100
  },
  {
    "id": 18,
    "region": "屏東",
    "job": "陽光巡遊騎士",
    "quote": "我家真的不在墾丁。",
    "zone": "南部",
    "bg": "#F4845F",
    "panel": "#F79B7F",
    "accent": "#843B25",
    "ink": "#203C32",
    "pattern": "sun",
    "sheet": "regions-03.png",
    "spriteX": 100,
    "spriteY": 100
  },
  {
    "id": 19,
    "region": "宜蘭",
    "job": "雨原結界師",
    "quote": "我是宜蘭，不是後花園。",
    "zone": "北部",
    "bg": "#6BBF7A",
    "panel": "#85CC92",
    "accent": "#2E6038",
    "ink": "#203C32",
    "pattern": "leaf",
    "sheet": "regions-04.png",
    "spriteX": 0,
    "spriteY": 0
  },
  {
    "id": 20,
    "region": "花蓮",
    "job": "車票閃現刺客",
    "quote": "搶到票，才能回家。",
    "zone": "東部",
    "bg": "#6EB5FF",
    "panel": "#8DC4FF",
    "accent": "#24568A",
    "ink": "#203C32",
    "pattern": "ticket",
    "sheet": "regions-04.png",
    "spriteX": 50,
    "spriteY": 0
  },
  {
    "id": 21,
    "region": "台東",
    "job": "慢活吟遊詩人",
    "quote": "等一下，先看海。",
    "zone": "東部",
    "bg": "#6EB5FF",
    "panel": "#8DC4FF",
    "accent": "#24568A",
    "ink": "#203C32",
    "pattern": "wave",
    "sheet": "regions-04.png",
    "spriteX": 100,
    "spriteY": 0
  },
  {
    "id": 22,
    "region": "澎湖",
    "job": "乘風船長",
    "quote": "我搭船，不騎海豚。",
    "zone": "離島",
    "bg": "#6EB5FF",
    "panel": "#8DC4FF",
    "accent": "#24568A",
    "ink": "#203C32",
    "pattern": "sail",
    "sheet": "regions-04.png",
    "spriteX": 0,
    "spriteY": 100
  },
  {
    "id": 23,
    "region": "金門",
    "job": "酒香鍛造師",
    "quote": "有高粱，不代表海量。",
    "zone": "離島",
    "bg": "#F4845F",
    "panel": "#F79B7F",
    "accent": "#843B25",
    "ink": "#203C32",
    "pattern": "jar",
    "sheet": "regions-04.png",
    "spriteX": 50,
    "spriteY": 100
  },
  {
    "id": 24,
    "region": "馬祖",
    "job": "燈塔傳令官",
    "quote": "我沒生氣，風比較大。",
    "zone": "離島",
    "bg": "#6EB5FF",
    "panel": "#8DC4FF",
    "accent": "#24568A",
    "ink": "#203C32",
    "pattern": "lighthouse",
    "sheet": "regions-04.png",
    "spriteX": 100,
    "spriteY": 100
  }
];
